using System;
using System.Collections.Generic;
using System.Text;

namespace Kaenx.Konnect.Enums
{
    public enum ApciTypes
    {
        Undefined = -1,
        GroupValueRead = 0x0,
        GroupValueResponse = 0x40,
        GroupValueWrite = 0x80,
        IndividualAddressWrite = 0xC0,
        IndividualAddressRead = 0x100,
        IndividualAddressResponse = 0x140,
        ADCRead = 0x180,
        ADCResponse = 0x1C0,
        SystemNetworkParameterRead = 0x1C8,
        SystemNetworkParameterWrite = 0x1CA,
        SystemNetworkParameterResponse = 0x1C9,
        MemoryRead = 0x200,
        MemoryResponse = 0x240,
        MemoryWrite = 0x280,
        UserMemoryRead = 0x2C0,
        UserMemoryResponse = 0x2C1,
        UserMemoryWrite = 0x2C2,
        UserMemoryBitWrite = 0x2C4,
        UserManufacturerInfoRead = 0x2C5,
        UserManufacturerInfoResponse = 0x2C6,
        FunctionPropertyCommand = 0x2C7,
        FunctionPropertyStateRead = 0x2C8,
        FunctionPropertyStateResponse = 0x2C9,
        DeviceDescriptorRead = 0x300,
        DeviceDescriptorResponse = 0x340,
        Restart = 0x380,
        OpenRoutingTable = 0x3C0,
        ReadRoutingTable = 0x3C1,
        ReadRoutingTableResponse = 0x3C2,
        WriteRoutinTable = 0x3C3,
        ReadRouterMemory = 0x3C8,
        ReadRouterMemoryResponse = 0x3C9,
        WriteRouterMemory = 0x3CA,
        ReadRouterStatus = 0x3CD,
        ReadRouterStatusResponse = 0x3CE,
        WriteRouterStatus,
        MemoryBitWrite,
        AuthorizeRequest,
        AuthorizeResponse,
        KeyWrite,
        KeyResponse,
        PropertyValueRead,
        PropertyValueResponse,
        PropertyValueWrite,
        PropertyDescriptionRead,
        PropertyDescriptionResponse,
        NetworkParameterRead,
        NetworkParameterResponse,
        IndividualAddressSerialNumberRead,
        IndividualAddressSerialNumberResponse,
        IndividualAddressSerialNumberWrite,
        DomainAddressWrite,
        DomainAddressRead,
        DomainAddressResponse,
        DomainAddressSelectiveRead,
        NetworkParameterWrite,
        LinkRead,
        LinkResponse,
        LinkWrite,
        GroupValueRead2,
        GroupValueResponse2,
        GroupValueWrite2,
        GroupValueInfoReport,
        DomainAddressSerialNumberRead,
        DomainAddressSerialNumberResponse,
        DomainAddressSerialNumberWrite,
        FileStreamInfoReport,
        Connect = 0x8000,
        Disconnect = 0x8100,
        Ack = 0x8200, //TODO remove last byte
        NAK = 0x8300, //TODO remove last byte
    }
}
